### ISSUE TITLE
Publication now appeared in Diachronica, so the dataset can be added to the Diacrhonica community

### ISSUE THREAD

**Issue by LinguList** [lexibank/yangyi#2]
Either one could make a new release, or one could just add it to the community.

**Comment by LinguList** [comment]
We need to release the data and update how to quote the dataset. So this would be version 1.2 then.

**Comment by LinguList** [comment]
[10.1075/dia.19062.yan](https://doi-org/10.1075/dia.19062.yan)

**Comment by LinguList** [comment]
@johenglisch or @chrzyki, would any of you two have time to look into this in this week? Otherwise I'd do it.

**Comment by xrotwang** [comment]
Both on holiday this week.

Johann-Mattis List ***@***.***> schrieb am Mo., 30. Mai 2022,
08:56:
